let gulp = require('gulp'),
    rename = require('gulp-rename'),
    sass = require('gulp-sass')(require('node-sass')),
    autoprefixer = require('gulp-autoprefixer'),
    sourcemaps = require('gulp-sourcemaps'),
    browserSync = require('browser-sync').create(),
    htmlmin = require('gulp-htmlmin');


const options = {
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  collapseWhitespace: true
};

function comScssInMiniCss(done) { //compilation Scss in Minification Css

	gulp.src('./resource/scss/**/*')
	  .pipe(sourcemaps.init())
	  .pipe( sass({
	  	errorLogToConsole: true,
	  	outputStyle: 'compressed'
	  }) )
	  .on('error', console.error.bind(console))
	  .pipe( autoprefixer({
	  	overrideBrowserslist: "last 2 versions"
	  }) )
	  .pipe( rename({suffix: '.min'}) )
	  // .pipe(sourcemaps.write('./'))
	  .pipe(sourcemaps.write())
	  .pipe( gulp.dest('./public/css/') )
	  .pipe(browserSync.stream());

	done();
}

function miniHtml(done) {

	gulp.src("./resource/html/**/*")
	  .pipe(sourcemaps.init())
	  .pipe(htmlmin({
	     collapseWhitespace: true 
	   }))
	  .on('error', console.error.bind(console))
	  .pipe(rename("index.html"))
	  .pipe(sourcemaps.write())
	  .pipe(gulp.dest('./'))
	  .pipe(browserSync.reload());

	done();

}

function browserReload(done) {
	browserSync.reload();
	done();
}

function server(done) {
	browserSync.init({
		server: {
			baseDir: "./"
		},
		port: 3000
	});
	done();
}

function watchFiles() {
	gulp.watch('./resource/scss/**/*', comScssInMiniCss);
	gulp.watch('./**/*.html', miniHtml);
	gulp.watch('./**/*.php', browserReload);
	gulp.watch('./**/*.js', browserReload);
}

gulp.task('default', gulp.parallel(server, gulp.series(comScssInMiniCss, watchFiles)));

// exports.def = defaultSomeTask;

// Bootstrap 5
// https://www.youtube.com/watch?v=kaLZgD-Ctss&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=1
// https://www.youtube.com/watch?v=z6a2BGeYwpk&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=2 
// https://www.youtube.com/watch?v=5Q-lv5xuFu0&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=3 
// https://www.youtube.com/watch?v=cyyy1nisy1I&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=4 
// https://www.youtube.com/watch?v=EP4qGTSEs4U&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=5 
// https://www.youtube.com/watch?v=A6r6c5aX4XE&list=PLD-piGJ3Dtl3qZFKzosT47lCCMEcqMK_L&index=6


  